version: '3.9'

services:
  api:
    image: cleanarchcqrs:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - ConnectionStrings:DefaultConnection=Server=db,1433;Database=CleanArchCqrs;User=sa;Password=sa
  db:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      SA_PASSWORD: sa 
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
    volumes:
      - db_data:/var/opt/mssql
    command: "--name CleanArchCqrs"

volumes:
  db_data:  # Volume para persistir os dados do banco de dados
